version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  gitai: gitai/gitai_orb@volatile

jobs:
  lint:
    docker:
      - image: gitaiinc/gitai-style
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - gitai/lint
      - slack/status

  melodic:
    docker:
      - image: gitaiinc/gitai-ci:melodic
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - gitai/test:
          cache_prefix: cache-melodic
          catkin_install: true
      - slack/status

  noetic:
    docker:
      - image: gitaiinc/gitai-ci:noetic
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - gitai/test:
          cache_prefix: cache-noetic
          catkin_install: true
      - slack/status

  lint-clang-tidy:
    docker:
      - image: gitaiinc/gitai-style
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - gitai/lint_clang_tidy
      - slack/status
workflows:
  review:
    jobs:
      - lint:
          context: gitai_ci
  tests:
    jobs:
      - melodic:
          context: gitai_ci
      - noetic:
          context: gitai_ci
      - lint-clang-tidy:
          context: gitai_ci
          requires:
            - noetic
          pre-steps:
            - attach_workspace:
                at: ~/
